set(_CATKIN_CURRENT_PACKAGE "simple_action_server")
set(simple_action_server_VERSION "0.0.0")
set(simple_action_server_MAINTAINER "Alex Bethel <Alexander.Bethel@student.nmt.edu>")
set(simple_action_server_PACKAGE_FORMAT "2")
set(simple_action_server_BUILD_DEPENDS "actionlib_msgs")
set(simple_action_server_BUILD_EXPORT_DEPENDS )
set(simple_action_server_BUILDTOOL_DEPENDS "catkin")
set(simple_action_server_BUILDTOOL_EXPORT_DEPENDS )
set(simple_action_server_EXEC_DEPENDS "actionlib_msgs" "message_generation")
set(simple_action_server_RUN_DEPENDS "actionlib_msgs" "message_generation")
set(simple_action_server_TEST_DEPENDS )
set(simple_action_server_DOC_DEPENDS )
set(simple_action_server_URL_WEBSITE "")
set(simple_action_server_URL_BUGTRACKER "")
set(simple_action_server_URL_REPOSITORY "")
set(simple_action_server_DEPRECATED "")