# Pitch action messages.

# Goal definition.

# True if the goal is to raise the pitch motors, such that the robot
# is prepared for digging; false if the goal is to lower them.
# 0 for home 1 for extend 3 for retract 4 for half
uint32 goal_state

---
# Result definition.
---
# Feedback definition.

# The progress towards being fully raised; approaches 1 if `raised` =
# true, or 0 if `raised` = false.
float64 progress
