#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

cd $(dirname "$0")
docker build .. -t lunabotics
yes | docker image prune || true

# Run a command in the container.
docker_run () {
    docker run \
           --volume $PWD/../ros:/lunabotics/ros \
           --volume $PWD/../utils:/lunabotics/utils \
           lunabotics /ros_entrypoint.sh \
           "$@"
}

# Build the Lunabotics code.
docker_run catkin_make "$@"

# Copy all the include directories out of the container, so that IDEs
# can work with them.
docker_run rm -r /lunabotics/ros/sys-include
docker_run cp -r /opt/ros/noetic/include /lunabotics/ros/sys-include
