#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

cd $(dirname "$0")
./build
docker run \
       --volume=$PWD/export:/export \
       --volume $PWD/../ros:/lunabotics/ros \
       --volume $PWD/../utils:/lunabotics/utils \
       --net=host \
       -it \
       lunabotics \
       /bin/bash
