#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

cd $(dirname "$0")

# wait_for_ros : Waits for ROS to launch.
wait_for_ros () {
    while ! rosservice list > /dev/null 2>&1; do
        echo 'waiting for ROS'
        sleep 1
    done
}

wait_for_ros

# Run rviz
rviz &
# Run rqt image view
# rosrun rqt_image_view rqt_image_view &
# Run plotter
# rosrun plotjuggler plotjuggler &
